ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: letsencrypt-prod
  tls:
    - hosts:
        - faas.wiput.me
      secretName: faas-wiput-me-tls
  hosts:
    - host: faas.wiput.me
      serviceName: gateway
      servicePort: 8080
      path: /
